[package]
name = "bingo/secret"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Reflex = "littensy/reflex@4.3.1"
Fusion = "elttob/fusion@0.3.0"
Sift = "csqrl/sift@0.0.9"
Remo = "littensy/remo@1.5.0"
Format = "kumarion/formatnumber@0.0.1"
Component = "sleitnick/component@2.4.8"
Loader = "sleitnick/loader@2.0.0"
t = "osyrisrblx/t@3.1.1"


[server-dependencies]
ProfileService = "grilme99/profileservice@1.0.0"
Cmdr = "evaera/cmdr@1.12.0"
